CPPFLAGS= -I/home/greg/devpt/libs/SFML2/include -I./include

LDFLAGS= -L/home/greg/devpt/libs/SFML2/lib -lsfml-system -lsfml-window -lsfml-graphics

CXXFLAGS= -g -Wall -Wextra -std=c++0x 

OBJS=src/BallsNBricks.o src/game/Game.o src/game/Ball.o src/game/LevelLoader.o src/game/Paddle.o src/game/Critter.o src/game/GameObjectsManager.o
NAME=BallsNBricks.exe

all:$(NAME)

$(NAME):$(OBJS)
	$(CXX) $(OBJS) -o $(NAME) $(LDFLAGS)

clean:
	rm $(NAME) $(OBJS)
